CREATE TABLE RELACION_EUR_USD (
   "ID" NUMBER NOT NULL ENABLE,
   "TIME" TIMESTAMP(6) NOT NULL ENABLE,
   "OPEN" NUMBER,
   "HIGH" NUMBER,
   "LOW" NUMBER,
   "CLOSE" NUMBER,
   "VOLUME" NUMBER,
   "LABEL" NUMBER,
   CONSTRAINT "RELACION_EUR_USD_PK PRIMARY" KEY ("ID") USING INDEX ENABLE
);